<a href="https://colab.research.google.com/github/pavana-p-kulal/Applications-of-Python-Programming-in-DA-and-ML/blob/master/Day_3_session_2_example_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10

In [5]:
import pandas as pd
#ds = pd.Series([2, 4, 6, 8..... 10]) 
print(ds)


0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to convert a Panda module Series to Python list and its type.

In [2]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [3]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [6]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)


Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}


In [7]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]


In [8]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']



In [9]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


Write a Pandas program to convert a given Series to an array.

In [10]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


Write a Pandas program to sort a given Series.

In [12]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)



Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


#Write a Pandas program to add some data to an existing Series.

In [13]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition.

In [14]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


Write a Pandas program to change the order of index of a given series.

In [15]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.



In [16]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565



#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}


In [17]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


Write a NumPy program to generate five random numbers from the normal distribution.

In [21]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[-1.28038091 -0.45304433  0.83524848 -2.30641628  1.88975303]


Write a NumPy program to generate six random integers between 10 and 30

In [22]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[29 14 23 16 16 11]


Write a NumPy program to create a 3x3x3 array with random values

In [23]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.51617269 0.37160302 0.02571586]
  [0.84995454 0.21828315 0.6183755 ]
  [0.95382175 0.72838787 0.3847637 ]]

 [[0.05965184 0.46480232 0.19377026]
  [0.00241625 0.1510388  0.87684015]
  [0.01696047 0.9574018  0.19357607]]

 [[0.66574202 0.92511844 0.30857935]
  [0.24528528 0.1577344  0.47604736]
  [0.29287134 0.34864999 0.98798393]]]


Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.



In [24]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.79409656 0.19278736 0.14475327 0.12631449 0.71464359]
 [0.54627486 0.11208336 0.37240425 0.04740316 0.83518675]
 [0.71033739 0.45212891 0.80485325 0.60901922 0.81076264]
 [0.03536496 0.31570491 0.42261337 0.56777982 0.05592399]
 [0.95583871 0.7671436  0.90059903 0.44074127 0.60224394]]
Minimum and Maximum Values:
0.03536495589823063 0.9558387093710513


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.

In [25]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)



Original array: 
[[0.01486549 0.25487745 0.62029076 0.98416122]
 [0.74485683 0.6626923  0.27925067 0.26531144]
 [0.11859257 0.91778291 0.63892608 0.92457873]
 [0.15281466 0.10561709 0.66127336 0.90107544]
 [0.89572839 0.23948824 0.4874379  0.48329765]
 [0.54425822 0.02600186 0.65968921 0.07134907]
 [0.34386945 0.28394834 0.78027081 0.88593917]
 [0.899821   0.28648015 0.71204639 0.783477  ]
 [0.16710573 0.68217686 0.97635512 0.6467338 ]
 [0.24277103 0.94691826 0.02674852 0.09538451]]
First 5 rows of the above array:
[[0.01486549 0.25487745 0.62029076 0.98416122]
 [0.74485683 0.6626923  0.27925067 0.26531144]
 [0.11859257 0.91778291 0.63892608 0.92457873]
 [0.15281466 0.10561709 0.66127336 0.90107544]
 [0.89572839 0.23948824 0.4874379  0.48329765]]
First 3 columns of the above array:
[[0.01486549 0.25487745 0.62029076 0.98416122]
 [0.74485683 0.6626923  0.27925067 0.26531144]
 [0.11859257 0.91778291 0.63892608 0.92457873]
 [0.15281466 0.10561709 0.66127336 0.90107544]
 [0.89572839 0.2394

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

In [26]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[1 6 4 7 5 2 3 9 0 8]
Same result using permutation():
[1 5 3 0 6 7 2 9 4 8]


Write a NumPy program to create a random integer nos of size 10 and sort it.

In [34]:
import numpy as np
x=np.arange(10)
np.random.randint(10)
print (x)


[0 1 2 3 4 5 6 7 8 9]


Write a NumPy program to create a random integer nos of size 10 and sort it.

In [31]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)



[7 9 3 1 0 5 4 6 8 2]
[0 1 2 3 4 5 6 7 8 9]
